services:
  ts-web-backend-template:
    container_name: ts-web-backend-template
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - PORT=${BACKEND_PORT}
      - NODE_ENV=${APP_ENV}
    ports:
      - '${BACKEND_PORT:-5000}:5000'
      - '${DEBUG_BACKEND_PORT:-9229}:9229'
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
